### ISSUE TITLE
support IPv6 localhost adress

### ISSUE THREAD

**Issue by LukevdPalen** [baminteractive/express-ipfilter#10]
In the recent version of Node and Express  4.0.0,  `req.connection.remoteAddress` returns `::1` and this is currently not supported in this module.

see my comment on https://github.com/baminteractive/express-ipfilter/commit/cc7de42e62790befc3c545e34efb66d7c8fe479f#diff-0d88c891ffe77973a1401c66be34ce38R78 line 78

**Comment by rv-kip** [comment]
Related https://github.com/joyent/node/issues/9195
