### ISSUE TITLE
Not able to use CIDR's in combination with regular IP's  anymore

### ISSUE THREAD

**Issue by LukevdPalen** [baminteractive/express-ipfilter#12]
The module isn't supporting multiple ip's in combination with CIDR's anymore, latest version dropped this "feature".

**Comment by ryanbillingsley** [comment]
@LukevdPalen can you provide the steps that produced this?  I will try and set up a test case and take a look at it today

**Comment by LukevdPalen** [comment]
Right now i only support one format. I our case we're using it to whitelist multiple addresses and formats. 
For example:
`[12.7.0.0.1, '192.168.1.3/28', ['127.0.0.3', '127.0.0.35']]`

**Comment by ryanbillingsley** [comment]
@LukevdPalen I don't think it was intentional.  I will take a look at it today.

**Comment by ryanbillingsley** [comment]
@LukevdPalen Can you pull down #13 and see if that fixes your problem?

**Comment by LukevdPalen** [comment]
This will do the job, but will introduce errors with local IPv6 addresses.
The `isPrivate` method in the node-ip module your where previous using will validate this as an local ip adres. Right now this functionality for allowing local ip is missing still the configuration parameter is still there.
