### ISSUE TITLE
This module is insecure and therefore useless

### ISSUE THREAD

**Issue by Rob--W** [baminteractive/express-ipfilter#15]
This library assumes that it may be behind a proxy, and blindly trusts the request headers: https://github.com/baminteractive/express-ipfilter/blob/5161db16503964b980fa143c8b8d61c436040571/lib/ipfilter.js#L62-L64

Since `X-Forwarded-For` and `CF-Connecting-IP` can be added by any client, the fact that the library relies on it makes it useless for access control. To fix the issue, do not use these request headers, and add an option to use these headers ONLY IF set by the developer.

**Comment by ryanbillingsley** [comment]
Open to a PR to address this.

**Comment by Rob--W** [comment]
I just reported the issue to raise awareness of the problem. I'm not going to submit a PR for the lack of time, even though the patch itself is trivial.

The next user who cares is of course free to submit the PR.
