### ISSUE TITLE
Messes up IPv6

### ISSUE THREAD

**Issue by nordisk** [baminteractive/express-ipfilter#17]
Hi.
I really like this module … but it messes up with IPv6, which is now standard on the `net` module of Node v4 …

https://github.com/baminteractive/express-ipfilter/blob/master/lib/ipfilter.js#L88

**Comment by ryanbillingsley** [comment]
@nordisk there is a PR to support IPv6 but it needs tests to support it.  

I haven't had time to look at it lately but I will try and get it in soon.

**Comment by ryanbillingsley** [comment]
I pushed a fix for this, feel free to re-open if you are still having problems
