### ISSUE TITLE
Shut off verbose Logging?

### ISSUE THREAD

**Issue by nuclearspike** [baminteractive/express-ipfilter#20]
I'd like to have an option to shut off the logging. When I'm blacklisting, I'd only want to see attempts from the blacklisted IP show up in the logs, but it's logging every single request from every single IP telling me it granted them access. That's way more than I was wanting. How can I shut this off without uninstalling?

**Comment by nuclearspike** [comment]
nm, I looked through the tests to see the { log: false } setting. That should be in the readme.

**Comment by ryanbillingsley** [comment]
The options were added to the readme
