### ISSUE TITLE
improve filter ranges with dash notation

### ISSUE THREAD

**Issue by Freundschaft** [baminteractive/express-ipfilter#24]
hey, thanks for the library!

I wanted to ask if would be possible to add a feature in order to filter like this:

['80.150.69.1-80.150.69.55']

Thanks & Cheers
Qiong

**Comment by ryanbillingsley** [comment]
@Freundschaft is there a particular reason that the current range syntax won't work?

From the docs:
> Using IP ranges:

> var ips = [['127.0.0.1','127.0.0.10']];

> // Create the server
> app.use(ipfilter(ips, {mode: 'allow'}));
> app.listen(3000);

**Comment by Freundschaft** [comment]
ah okay I didnt understand how this was supposed to be used, its understood now.

**Comment by ryanbillingsley** [comment]
@Freundschaft no worries, glad I could help :+1:
