### ISSUE TITLE
This could be easily bypassed

### ISSUE THREAD

**Issue by carloslopez1990** [baminteractive/express-ipfilter#25]
Since u r using x-forwarded-for header and headers can of course be modified, creating random ip addresses and sending them through x-forwarded-for is possible...

**Comment by SCBuergel** [comment]
you could just as well use a VPN and avoid any detection altogether. I think the point is to provide an easy to use filter that blocks most "common" web traffic.

**Comment by carloslopez1990** [comment]
using a VPN you have the same problem as using proxy... u get only one IP, if you use multiples proxys then get multiples IP's but still limited, but using x-forwarded-for and random ip addresses, u have all the ip's u want... so "using a VPN" is not as evil as the method i described, i'm talking for example of scenarios like form automation, web scrapping and more...

**Comment by ryanbillingsley** [comment]
@carloslopez1990 I am working on a new version that will make forwarded IPs disabled by default and only if you enable them will they then be used. This goes for CloudFlare and Codio as well.

**Comment by ryanbillingsley** [comment]
Please see https://github.com/baminteractive/express-ipfilter/pull/26 for the change.
