### ISSUE TITLE
0.1.0 introduced localhost issue

### ISSUE THREAD

**Issue by AdamGerthel** [baminteractive/express-ipfilter#28]
I just upgraded to 0.1.0 from 0.0.24 and noticed that the localhost address has changed, which in my case made my application block localhost. I solved it in OSX by using `::ffff:127.0.0.1` but on Windows under IISNode the localhost IP seems to be and empty string (`Access denied to IP address: `). Allowing an empty string in the array of allowed IPs seems to allow any IP.

Is there an issue with fetching the localhost IP properly?

**Comment by ryanbillingsley** [comment]
I'm not sure but I will check it out tomorrow and see what I can figure out

Sent from my iPhone

On Aug 21, 2016, at 7:26 AM, Adam Gerthel <notifications@github.com<mailto:notifications@github.com>> wrote:


I just upgraded to 0.1.0 from 0.0.24 and noticed that the localhost address has changed, which in my case made my application block localhost. I solved it in OSX by using ::ffff:127.0.0.1 but on Windows under IISNode the localhost IP seems to be and empty string (Access denied to IP address:). Allowing an empty string in the array of allowed IPs seems to allow any IP.

Is there an issue with fetching the localhost IP properly?

-

**Comment by ryanbillingsley** [comment]
@AdamGerthel the filter gets the requesting IP address from express which is part of the `req` object, specifically `req.connection.remoteAddress`. You might look to see if that exists when you are getting the request through IISNode by putting a middleware function before the filter and checking that property.

You might also check [this issue](https://github.com/tjanczuk/iisnode/issues/94) out, as it seems that IISNode might not populate that property and you would have to use the `allowFoward` setting on `ipFilter` to check the `x-forwarded-for` header for the ip.

**Comment by AdamGerthel** [comment]
Thanks, I'll give it a try!

**Comment by ryanbillingsley** [comment]
I am going to go ahead and close this but feel free to open it if there is still a problem
