### ISSUE TITLE
Support for logging only denials

### ISSUE THREAD

**Issue by AdamGerthel** [baminteractive/express-ipfilter#31]
My log is quickly filling up with "Access granted" entries. I could turn off logging entirely, but for security purposes I would like to be able to see denied access attempts. How about adding an option be more specific in terms of logging? For example via a new option (string) `logLevel` with options of `all|deny|allow` defaulting to `all`.

**Comment by longstone** [comment]
that makes sense ;)
I'll give a try

**Comment by ryanbillingsley** [comment]
Merged in #32 which should fix this
