### ISSUE TITLE
This breaks on ipv4 => ipv6 conversion

### ISSUE THREAD

**Issue by Aedaeum** [baminteractive/express-ipfilter#43]
In my express app, ipv4 IPs are represented by `::ffff:255.255.255.255` which is their ipv6 alternative. This causes the ipfilter to break as it doesn't know how to handle the `::ffff:` prefix. I've cheated by hard-coding this into the ipfilter for now, but it would be nice if you could add this as a core filter.

The hard-code I used is as folows:
```javascript
if (~ipAddress.indexOf('::ffff:')) {
  ipAddress = ipAddress.split('f:')[1];
}
    
if (ipAddress == '::1') {
  ipAddress = '127.0.0.1'
}
```

I should add that I've not read the ipv6 spec, so I'm not sure if this is the **proper** way to filter the converted ipv4's.

**Comment by longstone** [comment]
+1

**Comment by ryanbillingsley** [comment]
I just merged #44 which should fix this problem. If you are still having issues with the new version, feel free to reopen.

**Comment by Aedaeum** [comment]
@ryanbillingsley This fixes the overall issue, but does not resolve the `::1` ip reserved for localhost connections.

**Comment by ryanbillingsley** [comment]
@Aedaeum you can't just add `::1` to your list of IPs?

**Comment by Aedaeum** [comment]
@ryanbillingsley Yes, I can. I just figured it would be more intuitive from a programming perspective to have `127.0.0.1` handle all localhost connections.

**Comment by ryanbillingsley** [comment]
@Aedaeum my only concern is making any assumptions about how an IP should be handled. I agree with you that it would make sense that if you had the one, just honor the other, but if that created an issue for someone else and they weren't expecting it, that would seem to be worse than having to add both the IPv4 and IPv6 addresses.

**Comment by Aedaeum** [comment]
@ryanbillingsley I agree with that. I'm not sure about the ramifications either.
