### ISSUE TITLE
Error on Access Denied

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [baminteractive/express-ipfilter#53]
Whenever an IP is denied access - One gets an error message
```
 name: 'IpDeniedError',
  message: 'Access denied to IP address: 127.0.0.2',
  extra: undefined }
```
How does one get rid of the "undefined }" error message.

**Comment by ryanbillingsley** [comment]
@VinayaSathyanarayana are you talking about `extra` being undefined?

**Comment by ryanbillingsley** [comment]
Closing this until we hear more back
