### ISSUE TITLE
Update IP block list

### ISSUE THREAD

**Issue by mayeaux** [baminteractive/express-ipfilter#58]
I'd like to update the IP block list on the fly, is there a good way to do this while still using it as an express middleware? Thanks

**Comment by Chalarangelo** [comment]
I would also like to know if this is possible somehow.

**Comment by ludetc** [comment]
It's in the documentation:

> Using a function to get Ips:

var ips = function() { return ['127.0.0.1']; };

// Create the server
app.use(ipfilter(ips, {mode: 'allow'}));

module.exports = app;

Works great.
